@baseUrl=http://localhost:{{$dotenv PORT}}
@authToken={{logar.response.body.token}}

@userEmail=teste@teste.com
@userPasswd=teste@123

# @name logar
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{userEmail}}",
  "password": "{{userPasswd}}"
}

###

# @name register-user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Teste Teste",
  "email": "{{userEmail}}",
  "password": "{{userPasswd}}"
}
